### ISSUE TITLE
Add .env example to backend directory

### ISSUE THREAD

**Issue by nat236919** [nat236919/tavern#7]
### Add .env example to backend directory

On **_/tavern/tavern-backend/_**, .**env** file example is not yet added. Please create and add the following variables to the **.env** file

Expected result **/tavern/tavern-backend/.env**
```.env
APP_VERSION = ''
APP_TITLE = ''
APP_DESCRIPTION = ''
APP_URL = ''
APP_PORT = ''
APP_DEBUG = True
APP_SECRET_KEY = ''

MONGO_ROOT_USER = ''
MONGO_ROOT_PASSWORD = ''
MONGO_DATABASE = ''
MONGO_COLLECTION = ''

MONGOEXPRESS_LOGIN = ''
MONGOEXPRESS_PASSWORD = ''
```

**NOTES:** 

- Please create a PR to the **dev** branch
- Follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by kaustav202** [comment]
I'd like to work on this @nat236919
