### ISSUE TITLE
Create a variable holding Collection Name

### ISSUE THREAD

**Issue by nat236919** [nat236919/tavern#9]
### Create a variable holding the Collection Name

On https://github.com/nat236919/tavern/blob/main/mongo-init/init.js, please create a variable holding an initial collection name

```js
let collName = "scrolls"
.
.
.
db.createCollection(collName , { capped: false });
```

**NOTES:** 

- Please create a PR for the **dev** branch
- Follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
    - ex.) `refactor: create a separate var holding the initial collection name (#{issue_num})`

**Comment by kaustav202** [comment]
can I take this up @nat236919 ?
